[package]
name = "triblespace-paths"
version = "0.47.0"
authors = ["Jan Bramkamp <crest@rlwinm.de>", "⚫️ <jp@bultmann.eu>", "Vanja Sophie Cangalovic <vanja@bultmann.eu>"]
edition = "2021"
rust-version = "1.89"
description = "Exact regular-path indexes for TribleSpace."
homepage = "https://trible.space"
license = "MIT OR Apache-2.0"
documentation = "https://docs.rs/triblespace-paths"
repository = "https://github.com/triblespace/triblespace-rs"

[dependencies]
triblespace-core = { version = "0.47.0", path = "../triblespace-core", default-features = false }

[dev-dependencies]
ed25519-dalek = "2.1.0"
futures = "0.3"

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(kani)'] }
